
name: homeassistant
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    network_mode: host
    volumes:
      - /mnt/docker/homeassistant/config:/config
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW

  matterserver:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matterserver
    network_mode: host
    volumes:
      - /mnt/docker/matterserver:/data
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW

  musicassistant:
    image: ghcr.io/music-assistant/server:latest
    container_name: musicassistant
    network_mode: host
    volumes:
      - /mnt/docker/musicassistant:/data
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket:ro
    restart: unless-stopped
    