arch: amd64
cores: 2
features: nesting=1,fuse=1
hostname: homeassistant
memory: 2048
onboot: 1
ostype: debian
swap: 4096
lxc.mount.entry: /tmp/bluetooth_proxy.sock tmp/bluetooth_proxy.sock none bind,create=file
lxc.mount.entry: /var/lib/bluetooth var/lib/bluetooth none bind,create=dir
lxc.mount.entry: /tmp/dbus_proxy.sock tmp/dbus_proxy.sock none bind,create=file

